version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-from-source-cython2:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            python -m pip install 'Cython<3'
            python -m pip install --use-feature=in-tree-build ./PythonAPI
          name: Install From Source
      - run:
          command: |
            python tests/test_cases.py
          name: Run Simple Test Cases
          
  build-from-source-cython3:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            python -m pip install Cython==3.0.0a10
            python -m pip install --use-feature=in-tree-build ./PythonAPI
          name: Install From Source
      - run:
          command: |
            python tests/test_cases.py
          name: Run Simple Test Cases

  build-from-sdist-cython2:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            python -m pip install build
            python -m build --sdist ./PythonAPI
            python -m pip install 'Cython<3' -U
            python -m pip install --progress-bar off ./PythonAPI/dist/*.tar.gz
          name: Install From Distribution
      - run:
          command: |
            python tests/test_cases.py
          name: Run Simple Test Cases
          
  build-from-sdist-cython3:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            python -m pip install build
            python -m build --sdist ./PythonAPI
            python -m pip install 'Cython==3.0.0a10' -U
            python -m pip install --progress-bar off ./PythonAPI/dist/*.tar.gz
          name: Install From Distribution
      - run:
          command: |
            python tests/test_cases.py
          name: Run Simple Test Cases

workflows:
  main:
    jobs:
      - build-from-source-cython2
      - build-from-source-cython3
      - build-from-sdist-cython2
      - build-from-sdist-cython3
