name: Build and Publish

on:
  - workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}-${{ matrix.cibw_archs }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest # linux x86_64
            cibw_archs: x86_64
            cibw_skip: "pp*"
          - os: ubuntu-latest # linux arm64 gnu
            cibw_archs: aarch64
            cibw_skip: "pp* *musllinux*"
          - os: ubuntu-latest # linux arm64 musl
            cibw_archs: aarch64
            cibw_skip: "pp* *manylinux*"
          - os: windows-latest
            cibw_archs: AMD64 ARM64
            cibw_skip: "pp*"
          - os: macos-14
            cibw_archs: universal2
            cibw_skip: "pp*"

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux' && matrix.cibw_archs == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build wheels on ${{ matrix.os }}-${{ matrix.cibw_archs }}
        uses: pypa/cibuildwheel@v2.17
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.9"
          CIBW_SKIP: ${{ matrix.cibw_skip }}
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_TEST_COMMAND: python {project}/tests/test_cases.py
          CIBW_TEST_SKIP: "*-win_arm64 *-musllinux_aarch64"
        with:
          package-dir: ./PythonAPI

      - uses: actions/upload-artifact@v4
        with:
          name: pycocotools-${{ matrix.os }}-${{ matrix.cibw_archs }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  test_source:
    uses: ./.github/workflows/unittest.yml

  build_sdist:
    needs: test_source
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist ./PythonAPI

      - uses: actions/upload-artifact@v4
        with:
          name: pycocotools-sdist
          path: ./PythonAPI/dist/*.tar.gz

  publish:
    needs: [build_wheels, build_sdist]
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment
    environment: release
    # https://github.com/pypa/gh-action-pypi-publish#trusted-publishing
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R dist

      - uses: pypa/gh-action-pypi-publish@release/v1
